const ALERT='ALERT'
const REFECTH_CHATS='REFETCH_CHATS'
const NEW_ATTACHMENTS='NEW_ATTACHMENTS'
const NEW_MESSAGE_ALERT='NEW_MESSAGE_ALERT'
module.exports={ALERT,REFECTH_CHATS,NEW_ATTACHMENTS,NEW_MESSAGE_ALERT}